# coding: utf-8

"""
    arXiv submit

    API to submit papers to arXiv.

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_submit_client.models.authorship import Authorship

class TestAuthorship(unittest.TestCase):
    """Authorship unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Authorship:
        """Test Authorship
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Authorship`
        """
        model = Authorship()
        if include_optional:
            return Authorship(
                i_am_author = True,
                i_am_authorized_to_proxy = True,
                proxy = ''
            )
        else:
            return Authorship(
                i_am_author = True,
                i_am_authorized_to_proxy = True,
                proxy = '',
        )
        """

    def testAuthorship(self):
        """Test Authorship"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
