# coding: utf-8

"""
    arXiv submit

    API to submit papers to arXiv.

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_submit_client.models.set_metadata import SetMetadata

class TestSetMetadata(unittest.TestCase):
    """SetMetadata unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SetMetadata:
        """Test SetMetadata
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SetMetadata`
        """
        model = SetMetadata()
        if include_optional:
            return SetMetadata(
                title = '',
                authors = '',
                comments = '',
                abstract = '',
                report_num = 56,
                msc_class = '',
                acm_class = '',
                journal_ref = '',
                doi = ''
            )
        else:
            return SetMetadata(
        )
        """

    def testSetMetadata(self):
        """Test SetMetadata"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
