# coding: utf-8

"""
    arXiv submit

    API to submit papers to arXiv.

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_submit_client.models.agreed_to_policy import AgreedToPolicy

class TestAgreedToPolicy(unittest.TestCase):
    """AgreedToPolicy unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AgreedToPolicy:
        """Test AgreedToPolicy
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AgreedToPolicy`
        """
        model = AgreedToPolicy()
        if include_optional:
            return AgreedToPolicy(
                accepted_policy_id = 56
            )
        else:
            return AgreedToPolicy(
                accepted_policy_id = 56,
        )
        """

    def testAgreedToPolicy(self):
        """Test AgreedToPolicy"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
