# coding: utf-8

# flake8: noqa
"""
    arXiv submit

    API to submit papers to arXiv.

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from openapi_client.models.agreed_to_policy import AgreedToPolicy
from openapi_client.models.authorship import Authorship
from openapi_client.models.authorship_direct import AuthorshipDirect
from openapi_client.models.authorship_proxy import AuthorshipProxy
from openapi_client.models.category_change_result import CategoryChangeResult
from openapi_client.models.http_validation_error import HTTPValidationError
from openapi_client.models.set_categories import SetCategories
from openapi_client.models.set_license import SetLicense
from openapi_client.models.set_metadata import SetMetadata
from openapi_client.models.started import Started
from openapi_client.models.started_alter_exising import StartedAlterExising
from openapi_client.models.started_new import StartedNew
from openapi_client.models.validation_error import ValidationError
from openapi_client.models.validation_error_loc_inner import ValidationErrorLocInner
