# coding: utf-8

"""
    arXiv submit

    API to submit papers to arXiv.

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List
from typing import Optional, Set
from typing_extensions import Self

class SetLicense(BaseModel):
    """
    The sender of this request agrees to offer the submitted items under the statement in the license.
    """ # noqa: E501
    license_uri: StrictStr
    __properties: ClassVar[List[str]] = ["license_uri"]

    @field_validator('license_uri')
    def license_uri_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['http://creativecommons.org/licenses/by/4.0/', 'http://creativecommons.org/licenses/by-sa/4.0/', 'http://creativecommons.org/licenses/by-nc-sa/4.0/', 'http://creativecommons.org/licenses/by-nc-nd/4.0/', 'http://arxiv.org/licenses/nonexclusive-distrib/1.0/', 'http://creativecommons.org/publicdomain/zero/1.0/']):
            raise ValueError("must be one of enum values ('http://creativecommons.org/licenses/by/4.0/', 'http://creativecommons.org/licenses/by-sa/4.0/', 'http://creativecommons.org/licenses/by-nc-sa/4.0/', 'http://creativecommons.org/licenses/by-nc-nd/4.0/', 'http://arxiv.org/licenses/nonexclusive-distrib/1.0/', 'http://creativecommons.org/publicdomain/zero/1.0/')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SetLicense from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SetLicense from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "license_uri": obj.get("license_uri")
        })
        return _obj


