# coding: utf-8

"""
    arXiv submit

    API to submit papers to arXiv.

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from submit_client.submit_api import SubmitApi


class TestSubmitApi(unittest.TestCase):
    """SubmitApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SubmitApi()

    def tearDown(self) -> None:
        pass

    def test_accept_policy_post_v1_submission_submission_id_accept_policy_post(self) -> None:
        """Test case for accept_policy_post_v1_submission_submission_id_accept_policy_post

        Accept Policy Post
        """
        pass

    def test_assert_authorship_post_v1_submission_submission_id_assert_authorship_post(self) -> None:
        """Test case for assert_authorship_post_v1_submission_submission_id_assert_authorship_post

        Assert Authorship Post
        """
        pass

    def test_file_post_v1_submission_submission_id_files_post(self) -> None:
        """Test case for file_post_v1_submission_submission_id_files_post

        File Post
        """
        pass

    def test_get_submission_v1_submission_submission_id_get(self) -> None:
        """Test case for get_submission_v1_submission_submission_id_get

        Get Submission
        """
        pass

    def test_set_categories_post_v1_submission_submission_id_set_categories_post(self) -> None:
        """Test case for set_categories_post_v1_submission_submission_id_set_categories_post

        Set Categories Post
        """
        pass

    def test_set_license_post_v1_submission_submission_id_set_license_post(self) -> None:
        """Test case for set_license_post_v1_submission_submission_id_set_license_post

        Set License Post
        """
        pass

    def test_set_metadata_post_v1_submission_submission_id_set_metadata_post(self) -> None:
        """Test case for set_metadata_post_v1_submission_submission_id_set_metadata_post

        Set Metadata Post
        """
        pass

    def test_start_v1_start_post(self) -> None:
        """Test case for start_v1_start_post

        Start
        """
        pass


if __name__ == '__main__':
    unittest.main()
