# coding: utf-8

"""
    arXiv submit

    API to submit papers to arXiv.

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from submit_client.service_api import ServiceApi


class TestServiceApi(unittest.TestCase):
    """ServiceApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServiceApi()

    def tearDown(self) -> None:
        pass

    def test_get_service_status_v1_status_get(self) -> None:
        """Test case for get_service_status_v1_status_get

        Get Service Status
        """
        pass


if __name__ == '__main__':
    unittest.main()
