# coding: utf-8

"""
    arXiv submit

    API to submit papers to arXiv.

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from submit_client.post_submit_api import PostSubmitApi


class TestPostSubmitApi(unittest.TestCase):
    """PostSubmitApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PostSubmitApi()

    def tearDown(self) -> None:
        pass

    def test_mark_deposited_post_v1_submission_submission_id_mark_deposited_post(self) -> None:
        """Test case for mark_deposited_post_v1_submission_submission_id_mark_deposited_post

        Mark Deposited Post
        """
        pass

    def test_mark_processing_for_deposit_post_v1_submission_submission_id_mark_processing_for_deposit_post(self) -> None:
        """Test case for mark_processing_for_deposit_post_v1_submission_submission_id_mark_processing_for_deposit_post

         Mark Processing For Deposit Post
        """
        pass

    def test_unmark_processing_for_deposit_post_v1_submission_submission_id_unmark_processing_for_deposit_post(self) -> None:
        """Test case for unmark_processing_for_deposit_post_v1_submission_submission_id_unmark_processing_for_deposit_post

        Unmark Processing For Deposit Post
        """
        pass


if __name__ == '__main__':
    unittest.main()
