# coding: utf-8

"""
    arXiv submit

    API to submit papers to arXiv.

    The version of the OpenAPI document: 0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
from inspect import getfullargspec
import json
import pprint
import re  # noqa: F401
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Optional
from openapi_submit_client.models.authorship_direct import AuthorshipDirect
from openapi_submit_client.models.authorship_proxy import AuthorshipProxy
from typing import Union, Any, List, Set, TYPE_CHECKING, Optional, Dict
from typing_extensions import Literal, Self
from pydantic import Field

AUTHORSHIP_ANY_OF_SCHEMAS = ["AuthorshipDirect", "AuthorshipProxy"]

class Authorship(BaseModel):
    """
    Authorship
    """

    # data type: AuthorshipDirect
    anyof_schema_1_validator: Optional[AuthorshipDirect] = None
    # data type: AuthorshipProxy
    anyof_schema_2_validator: Optional[AuthorshipProxy] = None
    if TYPE_CHECKING:
        actual_instance: Optional[Union[AuthorshipDirect, AuthorshipProxy]] = None
    else:
        actual_instance: Any = None
    any_of_schemas: Set[str] = { "AuthorshipDirect", "AuthorshipProxy" }

    model_config = {
        "validate_assignment": True,
        "protected_namespaces": (),
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_anyof(cls, v):
        instance = Authorship.model_construct()
        error_messages = []
        # validate data type: AuthorshipDirect
        if not isinstance(v, AuthorshipDirect):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AuthorshipDirect`")
        else:
            return v

        # validate data type: AuthorshipProxy
        if not isinstance(v, AuthorshipProxy):
            error_messages.append(f"Error! Input type `{type(v)}` is not `AuthorshipProxy`")
        else:
            return v

        if error_messages:
            # no match
            raise ValueError("No match found when setting the actual_instance in Authorship with anyOf schemas: AuthorshipDirect, AuthorshipProxy. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Dict[str, Any]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        # anyof_schema_1_validator: Optional[AuthorshipDirect] = None
        try:
            instance.actual_instance = AuthorshipDirect.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))
        # anyof_schema_2_validator: Optional[AuthorshipProxy] = None
        try:
            instance.actual_instance = AuthorshipProxy.from_json(json_str)
            return instance
        except (ValidationError, ValueError) as e:
             error_messages.append(str(e))

        if error_messages:
            # no match
            raise ValueError("No match found when deserializing the JSON string into Authorship with anyOf schemas: AuthorshipDirect, AuthorshipProxy. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], AuthorshipDirect, AuthorshipProxy]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


