from fastapi import FastAPI
from submit_ce.submit_fastapi.api.default_api import router as DefaultApiRouter
from .config import config

app = FastAPI(
    title="arxiv submit",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="0.1",
)
app.state.config = config

config.submission_api_implementation.setup_fn(config)
app.include_router(DefaultApiRouter)
