from fastapi import FastAPI
from .default_api import router as DefaultApiRouter

app = FastAPI(
    title="arxiv submit",
    description="No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)",
    version="0.1",
)

app.include_router(DefaultApiRouter)
